development:
  adapter: postgresql
  encoding: unicode
  database: port_development
  pool: 5
  username: root
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: port_test
  pool: 5
  username: root
  password: password